/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Array AST Node type
* by the ASTNode.java.ftl template
*/
package org.parsers.json.ast;

import org.parsers.json.*;
import java.util.*;
import static org.parsers.json.Token.TokenType.*;


public class Array extends BaseNode {
}


