/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for BooleanLiteral Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.json.ast;

import org.parsers.json.*;
import static org.parsers.json.Token.TokenType.*;


public class BooleanLiteral extends Literal {

    public BooleanLiteral(TokenType type, JSONLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


